### ISSUE TITLE
incorrect calculation of cyberlinks stat

### ISSUE THREAD

**Issue by mastercyb** [cyberFund/cybernode#143]
one of this lies:

<img width="1669" alt="Screen Shot 2022-09-07 at 09 52 48" src="https://user-images.githubusercontent.com/410789/188849145-ddb31660-4aae-4fe7-9300-bd2129604b3c.png">

<img width="815" alt="Screen Shot 2022-09-07 at 09 53 35" src="https://user-images.githubusercontent.com/410789/188849285-51eaa206-3f59-4f21-a09e-1af85a1cd619.png">

**Comment by maxim-uvarov** [comment]
I guess the bottom graph gets data from cyber index. And there are no cyberlinks from passport contract in cyber index. Top number is correct
<img width="684" alt="image" src="https://user-images.githubusercontent.com/4896754/188907138-bb595551-872c-4515-a315-a3b469199f45.png">

**Comment by maxim-uvarov** [comment]
related to:
- https://github.com/cybercongress/cyberindex/issues/14
- https://github.com/cybercongress/cyberindex/issues/15

**Comment by mrlp4** [comment]
> I guess the bottom graph gets data from cyber index. And there are no cyberlinks from passport contract in cyber index. Top number is correct <img alt="image" width="684" src="https://user-images.githubusercontent.com/4896754/188907138-bb595551-872c-4515-a315-a3b469199f45.png">

yep, top number pulled directly from node, last graph - from index

**Comment by mrlp4** [comment]
Fixed graph by changing to correct datasource
