### ISSUE TITLE
Move cybeindex to separate drive

### ISSUE THREAD

**Issue by mrlp4** [cyberFund/cybernode#152]
Move cybeindex to separate drive on Deimos api node.

**Comment by mrlp4** [comment]
Stop indexer (3 containers)
mount drive to tmp location
cp .cyberindex folder content to new drive
rename .cyberindex to something different
mount new drive to /root/.cyberindex
start containers
check status
add drive to fstab
rm old renamed cyberindex from main drive

**Comment by maximxmoroz** [comment]
mounted a new disk and rewrote the db on it, the node is working
