### ISSUE TITLE
Create snapshot usage guide 

### ISSUE THREAD

**Issue by mrlp4** [cyberFund/cybernode#153]
How to restore node from snapshot
include settings for indexer, pruning snapshots

**Comment by mrlp4** [comment]
Example: 
https://github.com/k0kk0k/cosmos-snapshots-doc/blob/main/osmosis.md

**Comment by maximxmoroz** [comment]
work is done, snapshot usage guide https://github.com/cybercongress/cybernode/blob/monitor/snapshot_guide.md
