### ISSUE TITLE
Setup automatic pruned snapshot creation for cyber

### ISSUE THREAD

**Issue by mrlp4** [cyberFund/cybernode#154]
https://github.com/c29r3/cosmos-snapshots 
node - juno

**Comment by maximxmoroz** [comment]
Automatic creation of snapshots for Cyber is configured 2 times a week using a script and will be shared at https://jupiter.cybernode.ai/shared/

**Comment by maximxmoroz** [comment]
https://github.com/maximxmoroz/script/blob/main/cyber_snapshot

**Comment by maximxmoroz** [comment]
done👍

**Comment by mrlp4** [comment]
@maximxmoroz bring pull request with script to cybernode repo

**Comment by maximxmoroz** [comment]
@mrlp4 https://github.com/cybercongress/cybernode/pull/170

**Comment by maximxmoroz** [comment]
https://github.com/cybercongress/cybernode/pull/187
