### ISSUE TITLE
Setup Axelar node 

### ISSUE THREAD

**Issue by mrlp4** [cyberFund/cybernode#162]
at io node
https://github.com/axelarnetwork/axelar-core
pruning to everything

**Comment by mrlp4** [comment]
https://quicksync.io/networks/axelar.html
use light snap for deploy

**Comment by maximxmoroz** [comment]
Axelar node setup on io

**Comment by mrlp4** [comment]
@maximxmoroz add endpoints (rpc, lcd and grpc) to README of cybernode and setup monitoring at IO

**Comment by maximxmoroz** [comment]
Add endpoints
https://github.com/cybercongress/cybernode/pull/164

**Comment by maximxmoroz** [comment]
configured monitoring of the Axelar node
https://cybernode.ai/grafana/d/4qQgLWoVz/axelar-dojo-1
