### ISSUE TITLE
Setup IPFS service uptime monitor

### ISSUE THREAD

**Issue by mrlp4** [cyberFund/cybernode#172]
At node io and comet, as systemd service uptime tracker.

**Comment by maximxmoroz** [comment]
Systemd service and monitoring is up on io and comet
https://cybernode.ai/grafana/d/io_dash/io?orgId=1

**Comment by mrlp4** [comment]
@maximxmoroz  Please move graphs to appropriate board, comet to comet, io to io

**Comment by maximxmoroz** [comment]
graphs moved to appropriate boards
