### ISSUE TITLE
Update endpoint uptimes monitoring

### ISSUE THREAD

**Issue by mrlp4** [cyberFund/cybernode#175]
- fix ipfs cluster uptime 
- add axelar API uptime

**Comment by maximxmoroz** [comment]
Done 
https://mimas.cybernode.ai/grafana/d/cyber_stats/computer
<img width="1427" alt="Снимок экрана 2023-05-22 в 15 04 33" src="https://github.com/cybercongress/cybernode/assets/79748212/0e449172-c868-4d92-9f8c-f66266601960">
