### ISSUE TITLE
cybernode graphana dashbord

### ISSUE THREAD

**Issue by mrlp4** [cyberFund/cybernode#177]
According to services in cybernode docker-compose create a bord with stats for very service.
- Bostrom node stats (without dev info)
- uptime ( block box exporter stat)
- ipfs stats (repo size, files pined)
- containers stats (uptime, ram cosumtion, [example](https://mimas.cybernode.ai/grafana/d/TKj0GSyWk/deimos?orgId=1&refresh=5m))
- nginx stats (requests, rate, check [here](https://mimas.cybernode.ai/grafana/d/c1tUm2n7z/cyb-ai?orgId=1&refresh=5s) for example)
- certificate monitoring ([example](https://mimas.cybernode.ai/grafana/d/xtkCtBkiz/https-endpoints-status?orgId=1&refresh=5s))

**Comment by maximxmoroz** [comment]
https://github.com/cybercongress/cybernode/pull/190
